name = "RootFinders"
uuid = "31562c0c-7283-11e9-0529-d7c919bc43d6"
authors = ["PieterAppeltans <pieter.appeltans@student.kuleuven.be>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
